name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t test . --file Dockerfile
      #run: docker tag test:latest naveenbn123/test:latest
     #docker push naveenbn123/test:latest
     #run: docker build . --file Dockerfile --tag test:latest naveenbn123/test:latest
      
    - uses: actions/checkout@v3
    - name: push Docker image
      #run: docker push naveenbn123/test:latest
