name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          username: naveenbn123
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
          password: dckr_pat_w_91aiCWq-Uqaf9I736cximtJcg
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: naveenbn123/test:app1
